extraction:
  cpp:
    after_prepare: 
      - python report.py 75
  cobol:
    after_prepare: 
      - python report.py 75
  csharp:
    after_prepare: 
      - python report.py 75
  java:
    after_prepare: 
      - python report.py 75
  javascript:
    after_prepare: 
      - python report.py 75
  python:
    after_prepare: 
      - python report.py 75
